name: Go Matrix
on: [push, pull_request]

jobs:

  cross:
    name: Go
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0

    strategy:
      matrix:
        go-version: [ 1.15, 1.16, 1.x ]
        # windows-latest failed because the suggested fixes tests don't ignore the famous Windows end of line (\r\n)
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod              # Module download cache
            ~/.cache/go-build         # Build cache (Linux)
            ~/Library/Caches/go-build # Build cache (Mac)
            '%LocalAppData%\go-build' # Build cache (Windows)
          key: ${{ runner.os }}-${{ matrix.go-version }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go-version }}-go-

      - name: Test
        run: go test -v -cover ./...

      - name: Build
        run: go build -v -ldflags "-s -w" -trimpath ./cmd/importas
